### ISSUE TITLE
Peer to peer code review week 4

### ISSUE THREAD

**Issue by DebbyMiressa** [UmerZia/Portfolio-Microverse#10]
Hi @UmerZia 👋 
**Your work was good, but the following are some of the suggestions that were raised during the peer-to-peer code review session.**

- Please could you adjust the headline section to be 100vh.
- Please add the navigation on the header inside a semantic tag (navbar).

**Comment by UmerZia** [comment]
Thanks @DebbyMiressa, I will fix the mentioned issue in my project. 😄
